%YAML:1.0
video_source: "rtsp://192.168.144.192:554/stream1" 

mode:
  width:  640
  height:  360
  optimize_fps:  1
  use_cuda:  1
  enhancer_enabled:  0
  roll_correction_enabled:  0
  stabilizer_enabled:  0

camera:
  threaded_queue_mode:  true
  colorspace: ""               
  logging:  true
  time_delay:  0
  thread_timeout:  5000

enhancer:

  brightness:  1.5
  contrast:  1.1
  

  enable_white_balance:  0
  wb_strength:  0.1

  enable_vibrance:  0
  vibrance_strength:  0.02

  enable_unsharp:  1
  sharpness:  2.0
  blur_sigma: 1.0              

  enable_denoise:  0
  denoise_strength:  10

  gamma:  1.2
  
  enable_clahe:  0
  clahe_clip_limit:  2.0
  clahe_tile_grid_size:  8
  
  use_cuda: true               

roll_correction:
  scale_factor:  0.25
  canny_threshold_low:  50
  canny_threshold_high:  150
  canny_aperture:  3
  hough_rho:  1.0
  hough_theta: 0.0174533      
  hough_threshold:  100
  angle_smoothing_alpha:  0.1
  angle_decay:  0.98
  angle_filter_min:  -70.0
  angle_filter_max:  70.0

stabilizer:
  smoothing_radius:  20
  border_type:  "replicate"
  border_size:  0
  crop_n_zoom:  0
  logging: true
  use_cuda: true 

