%YAML:1.0
video_source: "rtsp://192.168.144.119:554" 

mode:
  width:  1920
  height:  1080
  optimize_fps:  1
  use_cuda:  1
  tracker_enabled: 0
  enhancer_enabled:              0
  roll_correction_enabled:              0
  stabilizer_enabled:              1


camera:
  threaded_queue_mode:  true
  colorspace: ""               
  logging:  false
  time_delay:  0
  thread_timeout:  500
  queue_size: 5

enhancer:
  brightness:  1.5
  contrast:  1.1
  

  enable_white_balance:  0
  wb_strength:  0.1

  enable_vibrance:  0
  vibrance_strength:  0.02

  enable_unsharp:  1
  sharpness:  2.0
  blur_sigma: 1.0              

  enable_denoise:  0
  denoise_strength:  10

  gamma:  1.2
  
  enable_clahe:  0
  clahe_clip_limit:  2.0
  clahe_tile_grid_size:  8
  
  use_cuda: true               

roll_correction:
  scale_factor:  0.25
  canny_threshold_low:  50
  canny_threshold_high:  150
  canny_aperture:  3
  hough_rho:  1.0
  hough_theta: 0.0174533      
  hough_threshold:  100
  angle_smoothing_alpha:  0.1
  angle_decay:  0.98
  angle_filter_min:  -70.0
  angle_filter_max:  70.0

stabilizer:
  # Basic parameters - Real-time optimized stabilization
  smoothing_radius: 15            # Reduced for faster response
  border_type: "replicate"        # Border handling type
  fadeDuration: 30
  fadeAlpha: 0.9
  border_size: 10                  # Reduced border size for speed
  crop_n_zoom: true              # Disabled - Virtual Canvas handles sizing
  logging: true                   # Enable to see Virtual Canvas messages
  use_cuda: true
  max_corners: 150                # Reduced for performance
  quality_level: 0.02             # Slightly higher for better features
  min_distance: 20.0              # Better feature distribution
  block_size: 3
  
  smoothing_method: "gausian"       # box filter is fastest
  gaussian_sigma: 15.0          # Reduced for faster response
  
  # Multi-stage smoothing
  stage_one_radius: 30         # First stage smoothing
  stage_two_radius: 20         # Second stage smoothing
  use_temporal_filtering: true # Cross-frame smoothing
  temporal_window_size: 7      # Temporal filter window
  
  # Adaptive smoothing
  adaptive_smoothing: true
  min_smoothing_radius: 10
  max_smoothing_radius: 35
  
  # Professional motion analysis
  outlier_rejection: true
  outlier_threshold: 2.0       # Outlier rejection sensitivity
  
  # Motion prediction and intent detection (Action mode-like)
  motion_prediction: true
  intentional_motion_threshold: 15.0  # Panning detection threshold
  
  # Frequency-specific jitter filtering
  jitter_frequency: 3          # 0=LOW, 1=MEDIUM, 2=HIGH, 3=ADAPTIVE
  separate_translation_rotation: true # Handle separately
  
  # Professional scene adaptation
  deep_stabilization: false    # Advanced ML-based stabilization
  model_path: ""              # Path to stabilization model
  
  # IMU data integration (future feature)
  use_imu_data: false         # Incorporate IMU data if available
  
  # Roll compensation (flight/drone footage)
  roll_compensation: true
  roll_compensation_factor: 0.9
  
  # Region of Interest - optimized
  use_roi: true
  roi_x: 192      # Center region
  roi_y: 108
  roi_width: 1536 # 80% of frame
  roi_height: 864
  
  # Horizon lock - professional stabilization
  horizon_lock: true
  
  # Feature detector selection
  feature_detector_type: 0    # 0=GFTT, 1=ORB, 2=FAST, 3=BRISK
  fast_threshold: 15
  orb_features: 2000
  
  # Enhanced border effects
  border_scale_factor: 1.5    # Dynamic border scaling
  motion_threshold_low: 2.0   # Low motion threshold
  motion_threshold_high: 20.0 # High motion threshold
  
  # Professional motion classification thresholds
  shake_level_threshold: 3.0   # Camera shake detection
  walking_detection_threshold: 8.0  # Walking motion detection
  vehicle_detection_threshold: 15.0 # Vehicle vibration detection

  enable_virtual_canvas: true      # Enable virtual canvas stabilization
  canvas_scale_factor: 1.4         # Canvas size multiplier (larger for more visible edges)
  temporal_buffer_size: 8          # Number of frames in temporal buffer (reduced for speed)
  canvas_blend_weight: 0.6         # Blending weight for temporal regions
  adaptive_canvas_size: false      # Disable adaptive size for stability
  max_canvas_scale: 1.5           # Maximum canvas scale factor
  min_canvas_scale: 1.2           # Minimum canvas scale factor  
  preserve_edge_quality: false    # Disable for speed
  edge_blend_radius: 15           # Edge blending radius in pixels (larger for more visible edges)


deepstream_tracker:
  model_engine: "/home/orin/Developer/deepstream_engines/best.engine"
  model_config_file: "/home/orin/Developer/deepstream_engines/visconf.txt"
  tracker_config_file: "/opt/nvidia/deepstream/deepstream-7.1/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml"
  processing_width: 960
  processing_height: 544
  confidence_threshold: 0.1
  batch_size: 1
  debug_mode: true
