%YAML:1.0
video_source: "rtsp://192.168.144.119:554" 

mode:
  width:  1920
  height:  1080
  optimize_fps:  1
  use_cuda:  1
  tracker_enabled: 0
  enhancer_enabled:              0
  roll_correction_enabled:              0
  stabilizer_enabled:              0


camera:
  threaded_queue_mode:  true
  colorspace: ""               
  logging:  false
  time_delay:  0
  thread_timeout:  500
  queue_size: 5

enhancer:
  brightness:  1.5
  contrast:  1.1
  

  enable_white_balance:  0
  wb_strength:  0.1

  enable_vibrance:  0
  vibrance_strength:  0.02

  enable_unsharp:  1
  sharpness:  2.0
  blur_sigma: 1.0              

  enable_denoise:  0
  denoise_strength:  10

  gamma:  1.2
  
  enable_clahe:  0
  clahe_clip_limit:  2.0
  clahe_tile_grid_size:  8
  
  use_cuda: true               

roll_correction:
  scale_factor:  0.25
  canny_threshold_low:  50
  canny_threshold_high:  150
  canny_aperture:  3
  hough_rho:  1.0
  hough_theta: 0.0174533      
  hough_threshold:  100
  angle_smoothing_alpha:  0.1
  angle_decay:  0.98
  angle_filter_min:  -70.0
  angle_filter_max:  70.0

stabilizer:
  # Basic parameters - optimized for stability with good performance
  smoothing_radius: 5        # Increased back for better stability
  border_type: "replicate"    # Most efficient border type
  fadeDuration: 30
  fadeAlpha: 0.9
  border_size: 10             # Increased for better stability
  crop_n_zoom: 0
  logging: false              # Disable logging for performance
  use_cuda: true
  max_corners: 200            # Increased for better stability
  quality_level: 0.05         # Reduced for more features
  min_distance: 25.0          # Reduced for better feature distribution
  block_size: 3
  
  # SightLine-inspired parameters - balanced for stability
  smoothing_method: "gaussian" # Changed back to gaussian for better stability
  gaussian_sigma: 20.0        # Increased for more smoothing
  
  # Adaptive smoothing - enabled for better stability
  adaptive_smoothing: 1       # Re-enabled for better stability
  min_smoothing_radius: 15    # Increased minimum
  max_smoothing_radius: 35    # Increased maximum
  
  # Outlier rejection - enabled for stability
  outlier_rejection: true
  outlier_threshold: 2.0      # Reduced for more aggressive filtering
  
  # Motion prediction - enabled for smoother motion
  motion_prediction: 1        # Re-enabled for better stability
  intentional_motion_threshold: 0.9  # Increased threshold
  
  # Region of Interest - optimized for stability
  use_roi: true
  roi_x: 96       # Centered better
  roi_y: 54       # Centered better
  roi_width: 1728 # Full width for better tracking
  roi_height: 972 # Full height for better tracking
  
  # Horizon lock - enabled for stability
  horizon_lock: true          # Re-enabled for better stability
  
  # Feature detector - optimized for stability
  feature_detector_type: 0    # GFTT is most stable
  fast_threshold: 20          # Reduced for more features
  orb_features: 1500          # Increased for better tracking



deepstream_tracker:
  model_engine: "/home/orin/Developer/deepstream_engines/best.engine"
  model_config_file: "/home/orin/Developer/deepstream_engines/visconf.txt"
  tracker_config_file: "/opt/nvidia/deepstream/deepstream-7.1/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml"
  processing_width: 960
  processing_height: 544
  confidence_threshold: 0.1
  batch_size: 1
  debug_mode: true
